## name: aetheria
# author: Dizziee (https://github.com/jjdizz1l)
# variant: "dark"
background              #0e091d
foreground              #14B9B5
selection_foreground    #0e091d
selection_background    #14B9B5
cursor                  #ff7f41
cursor_text_color       #ff7f41
active_tab_foreground   #0e091d
active_tab_background   #14B9B5
inactive_tab_foreground #0e091d
inactive_tab_background #14B9B5

# black
color0  #000000
color8  #c53253

# red
color1  #E20342
color9  #CE4F48

# green
color2  #c8e967
color10 #f93d3b

# yellow
color3  #7cd699
color11 #FD3E6A

# blue
color4  #BE3F50
color12 #04C5F0

# magenta
color5  #9147a8
color13 #6C032C

# cyan
color6  #FF7F41
color14 #ffbe74

# white
color7  #A60234
color15 #11AEB3
